# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a91a4174d9ddc79e23c57d6086d17c8ebb4ad91b7b377efbedc4fcdc3ef78b5d31bd24b555a1685ed588708135e27ac8af76519bf402c9eec32efd04ee7560d

test:
  secret_key_base: baaa78219d2418117a716ce9a8571b5cfea7fba58d4c0d432374dc94453dd858da76369c97dfe25898db9cf6886328bdfeb6fcb40e562c747ecfca47a926ae64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
